### ISSUE TITLE
Badenjki\Seller Package Issue

### ISSUE THREAD

**Issue by suvo98** [Swakhar/bg_save_24#14]
in \packages\Webkul\Shop\src\Http\routes.php file 

 Route::group(['middleware' => ['web', 'locale', 'theme', 'currency']], function () {

        Route::group(['middleware' => ['customer']], function () {

            Route::get('stores', 'Badenjki\Seller\Http\Controllers\StoreController@index')->defaults('_config', [
                'view' => 'shop::customers.account.store.index'
            ])->name('customer.store.index');

            Route::get('stores/create', 'Badenjki\Seller\Http\Controllers\StoreController@create')->defaults('_config', [
                'view' => 'shop::customers.account.store.create'
            ])->name('customer.store.create');

            Route::post('stores/create', 'Badenjki\Seller\Http\Controllers\StoreController@store')->defaults('_config',[
                'redirect' => 'customer.store.index'
            ])->name('customer.store.create');

            Route::get('stores/edit/{id}', 'Webkul\Customer\Http\Controllers\AddressController@edit')->defaults('_config', [
                'view' => 'shop::customers.account.store.edit'
            ])->name('customer.store.edit');

            Route::patch('stores/edit/{store}', 'Badenjki\Seller\Http\Controllers\StoreController@update')->defaults('_config',[
                'redirect' => 'customer.store.index'
            ])->name('customer.store.edit');

        });
        Route::get('/{store}', 'Badenjki\Seller\Http\Controllers\StoreController@show');
    });

**if i comment  project run fine**

**but if i use those route then it show below error** 

what is miss when pull Add-vendor-functionality branch  not sure @Swakhar @Najmuzzaman 

![Screenshot (55)](https://user-images.githubusercontent.com/24931073/87511504-2fa62380-c697-11ea-99fd-a60b13ea8fc4.png)

**Comment by Swakhar** [comment]
@suvo98 , I have pushed again with my latest changes. Take pull again and check
